stages:
  - test

test:
  image: php:8.2
  stage: test
  script:
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - php vendor/bin/phpunit --testdox tests/
